spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        id:
          new_generator_mappings: false
  datasource:
    url: jdbc:h2:mem:voting
    username: sa
    password:
  h2:
    console:
      enabled: true
logging.level.root: OFF